version: "3.7"
services:
  FakeDns:
    container_name: FakeDns
    image: python:3.8
    command: /opt/FakeDns/fakedns.py -c /opt/FakeDns/dns.conf.example
    volumes:
      - ./:/opt/FakeDns
    ports: 
      - "5353:53/udp"